# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slm',
                'doc_host': 'https://misza222.github.io',
                'git_url': 'https://github.com/misza222/slm',
                'lib_path': 'slm'},
  'syms': {'slm.core': {'slm.core.foo': ('core.html#foo', 'slm/core.py')}}}